const headings = {
    storeName: "Store Name",
    UKSICAForm: "UKSICA Audit Form",
    UKSICAIntelligenceForm: "UK Intelligence Analysis Form",
    StoreInformation: "Store Information",
    StoreName: "Store Name",
    StoreAddress: "Address",
    NumberofAisles: "Number of Aisles",
    SecurityGuardDetails: "Security Guard Details",
    NumberOfSecurityGuards: "Number of Security Guards",
    SIABadgeVisible: "SIA Badge Visible?",
    CompanyLogoVisible: "Company Logo Visible?",
    ManagerDetails: 'Manager Details',
    ManagerName: 'Security Person Name',
    position: 'Position',
    awareOf: "Security Person Aware of Security Proc?",
    GDPRCompliance: "GDPR Compliance",
    IsGDPRController: 'Is GDPR Controller Information Available?',
    IsCCTVWarning: "CCTV Warning Sign Displayed?",
    FollowUpRequired: "Follow-up Required",
    AreIssues: "Any Issues That Require Immediate Attention?",
    SecurityRating: "Overall Security Rating",
    Isthereinformation: "Visible information?",
    securityGraudBehavior: "Security Guards' Behaviour and Professionalis?",
    GeneralObservations: 'General Observations',
    AdditionalObservations: "Additional Observations",
    ResponseTimeOfGuards: "Response Time of Guards to Issues",
    securityRating: "Overall Security Rating",
    addphotos: 'Add Relevant Photos',
    addSignature: 'Add Signature',
    errorMessage: "Something went wrong. Try again later.",
    UK: 'UK',
    SICA: ' SICA',
    login: 'Login',
    select: "Select User Type",
    form1: "Form 1",
    form2: "Form 2",
    successMessage: "Form submitted successfully! Thank you.",

    suspectedExploiter: "Suspected Exploiter(s)",
    nameAliases: "Name(s)/Alias(es)",
    dateOfBirth: "Date of Birth (if known)",
    nationalityEthnicity: "Nationality/Ethnicity",
    addresses: "Address(es)",
    contactDetails: "Contact Details (Phone/Email)",
    businessAffiliation: "Business/Organisation Affiliation",
    vehicleDetails: "Vehicle Details",
    subjectInformation: "Subject Information (if available)",
    languageSpoken: "Language(s) Spoken",
    SuspectedVictim: "Suspected Victim(s)",
    vulnerableCharacteristics: "Vulnerable Characteristics",

    LocationIncidentDetails: "Location/Incident Details",
    LocationOfSuspectedExploitation: "Location of Suspected Exploitation",
    DateTimeOfSuspectedExploitation: "Date(s)/Time(s) of Suspected Exploitation",
    TypeOfLocation: "Type of Location",
    DescriptionOfIncident: "Description of Incident/Observation",

    WorkingConditions: "Working Conditions",
    IndicatorsOfLabourExploitation: "Indicators of Labour Exploitation",
    excessiveWorkingHours: "Excessive working hours",
    unsafeWorkingConditions: "Unsafe working conditions",
    lackOfProtectiveEquipment: "Lack of protective equipment",
    restrictedMovement: "Restricted movement/confinement",
    poorLivingConditions: "Poor living conditions",
    PaymentControl: "Payment/Financial Control",
    nonPaymentOrUnderpayment: "Non-payment or underpayment of wages",
    wageDeductionsWithoutExplanation: "Deductions from wages without explanation",
    controlOfBankAccounts: "Control of bank accounts/documents",
    debtBondage: "Debt bondage",
    PsychologicatControl: "Psychological/Physical Control",
    threatsOrIntimidation: "Threats or intimidation",
    physicalAbuse: "Physical abuse",
    verbalAbuse: "Verbal abuse/humiliation",
    isolationFromOthers: "Isolation from others",
    fearOfAuthorities: "Fear of authorities",
    DocumentControl: "Document/Identity Control",
    confiscationOfDocuments: "Confiscation of passports/ID documents",
    restrictionOnCommunication: "Restriction on communication",
    falseDocuments: "False Documents",

    Recruitment: "Recruitment/Transportation",
    recruitmentTransportation: "Recruitment/Transportation",
    deceptiveRecruitment: "Deceptive recruitment practices",
    forcedTransportation: "Forced transportation",
    recruitmentFees: "Fees charged for recruitment or transportation",
    SupportingEvidence: "Supporting Evidence",
    WitnessStatements: "Witness Statements",
    PhotographsVideos: "Photographs/Videos",
    DocumentsRecords: "Documents/Records",
    AnyOtherRelevantInformation: "Any other relevant information",
    addFiles: "Attach relevant files",

    AssessmentofRisk: "Assessment of Risk",
    LikelyFormofExploitation: "Likely Form of Exploitation",
    PotentialLinkstoOrganisedCrime: "Potential Links to Organised Crime",
    AnyFurtherInvestigationNeeded: "Any further investigation needed",
    Justification: "Justification",
    Analysis: "Analysis",
    Recommendations: "Recommendations",
    internalAction: "Internal Action",
    externalReporting: "External Reporting",
    safeguardingMeasures: "Safeguarding Measures",
    doNotContact: "Do Not Contact",
    ReportingToExternalAgencies: "Reporting to External Agencies",
    agencyContacted: "Agency Contacted (Name/Organisation)",
    dateTimeContacted: "Date/Time Contacted",
    referenceNumber: "Reference Number (if provided)",
    outcomeActionTaken: "Outcome/Action Taken",
    Review: "Review and Sign-Off",
    dateReviewed: "Date Reviewed",
    reviewedBy: "Reviewed by (Name/Position)",
    sign: "Signature/Electronic Signature",
    
    ComplianceDetails:"Compliance Details",
    ReportingOfficer:"Reporting Officer(Name/id)",
    DateofReport:"Date of Report",
    ClientName:"Client Name/Location",
    CompanyName:"Company Name",













}
export default headings;