const headings={
    storeName:"Store Name",
    UKSICAForm:"UKSICA Audit Form",
    StoreInformation:"Store Information",
    StoreName:"Store Name",
    StoreAddress:"Address",
    NumberofAisles:"Number of Aisles",
    SecurityGuardDetails:"Security Guard Details",
    NumberOfSecurityGuards:"Number of Security Guards",
    SIABadgeVisible:"SIA Badge Visible?",
    CompanyLogoVisible:"Company Logo Visible?",
    ManagerDetails:'Manager Details',
    ManagerName:'Security Person Name',
    position:'Position',
    awareOf:"Security Person Aware of Security Proc?",
    GDPRCompliance:"GDPR Compliance",
    IsGDPRController:'Is GDPR Controller Information Available?',
    IsCCTVWarning:"CCTV Warning Sign Displayed?",
    FollowUpRequired: "Follow-up Required",
    AreIssues: "Any Issues That Require Immediate Attention?",    
    SecurityRating: "Overall Security Rating", 
    Isthereinformation:"Visible information?",
    securityGraudBehavior:"Security Guards' Behaviour and Professionalis?",
    GeneralObservations:'General Observations',
    AdditionalObservations:"Additional Observations",
    ResponseTimeOfGuards:"Response Time of Guards to Issues",
    securityRating:"Overall Security Rating",
    addphotos:'Add Relevant Photos',
    addSignature:'Add Signature',
   errorMessage:"Something went wrong. Try again later.",
   UK:'UK',
   SICA:' SICA',
   login:'Login',
   select:"Select User Type",
   form1:"Form 1",
   form2:"Form 2",
   successMessage:"Form submitted successfully! Thank you."

    
}
export default headings;